.TH [AIR] "1" "June 2023" "boDz" "User Commands"
.SH NAME
[air] \- air
.SH SYNOPSIS
.B air
[\fI\,OPTIONS\/\fR] \fI\,AI-IMAGE ARGS\/\fR...
.SH OPTIONS
.TP
\fB\-\-help\fR
Print this help page.
.TP
\fB\-\-version\fR
Print the version information.
.SH AUTHOR
Written by Lenik, Version 2.1.5, Last updated at 2023\-06\-01
