.TH ASCII-ART "1" "June 2023" "boDz" "User Commands"
.SH NAME
Ascii-Art \- unai
.SH DESCRIPTION
.SS "Usage:"
.IP
unai [OPTION?] FILES
.SS "Help Options:"
.TP
\fB\-h\fR, \fB\-\-help\fR
Show help options
.SS "Application Options:"
.TP
\fB\-c\fR, \fB\-\-stdout\fR
Write to stdout instead of the file
.TP
\fB\-k\fR, \fB\-\-keep\fR
Keep the original files, don't delete them
.TP
\fB\-i\fR, \fB\-\-keyfile\fR
A data file contains the key for encryption
.TP
\fB\-f\fR, \fB\-\-force\fR
Force to overwrite existing files
.TP
\fB\-q\fR, \fB\-\-quiet\fR
Show less verbose info
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Show more verbose info
.TP
\fB\-\-version\fR
Show version info
.SH AUTHOR
Written by Lenik, (at) 99jsj.com
